name: Lighthouse CI

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  lhci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build app
        run: bun run build

      - name: Start app
        run: |
          nohup bun run start -p 3002 > .next/next-start.log 2>&1 &

      - name: Wait for server
        run: |
          for i in {1..90}; do
            if curl -sSf http://localhost:3002 > /dev/null; then
              echo "Server is up"; break; fi
            echo "Waiting for server... ($i)"; sleep 1;
          done

      - name: Run Lighthouse CI
        run: npx --yes @lhci/cli@0.13.x autorun --config=.lighthouserc.js || echo "Lighthouse CI completed with warnings"

      - name: Upload LHCI artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lhci-results
          path: .lighthouseci
